subtracker_ui/frontend/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('oauth/', include("social_django.urls")),
#    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('subscriptions/', views.subscriptions, name='subscriptions'),
    path('profile/', views.profile, name='profile'),
#    path('user/', views.user, name='user'),
    ]

subtracker_ui/libs/social_django/urls.py
"""URLs module"""
from django.conf import settings
from django.conf.urls import url

from social_core.utils import setting_name
from . import views


extra = getattr(settings, setting_name('TRAILING_SLASH'), True) and '/' or ''

app_name = 'social'

urlpatterns = [
    # authentication / association
    url(r'^login/(?P<backend>[^/]+){0}$'.format(extra), views.auth,
        name='begin'),
    url(r'^complete/(?P<backend>[^/]+){0}$'.format(extra), views.complete,
        name='complete'),
    # disconnection
    url(r'^disconnect/(?P<backend>[^/]+){0}$'.format(extra), views.disconnect,
        name='disconnect'),
    url(r'^disconnect/(?P<backend>[^/]+)/(?P<association_id>\d+){0}$'
        .format(extra), views.disconnect, name='disconnect_individual'),
]

subtracker_ui/subtracker_frontend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('frontend.urls')),
    path('admin/', admin.site.urls),
]

subtracker_ui/frontend/models.py
from django.db import models

# Create your models here.

subtracker_ui/frontend/views.py
from django.http import HttpResponse
from django.contrib import auth
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.core.mail import send_mail
from django.conf import settings
import os

import logging
# create logger
logger = logging.getLogger('simple_example')
logger.setLevel(logging.DEBUG)

# create console handler and set level to debug
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)

# create formatter
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

# add formatter to ch
ch.setFormatter(formatter)

# add ch to logger
logger.addHandler(ch)

api_subscription_key = os.environ['api_subscription_key']

def index(request):
    return render(request, 'index.html')

def logout(request):
    auth.logout(request)
    return redirect('index')

@login_required(login_url='/oauth/login/azuread-b2c-oauth2/')
def profile(request):
    return render(request, 'profile.html')

import json, requests
@login_required(login_url='/oauth/login/azuread-b2c-oauth2/')
def subscriptions(request):
    if request.method == "POST":
        pass
    else:
        headers = {"Ocp-Apim-Subscription-Key": api_subscription_key}
        services = {}
        services_url = "https://api.subtracker.ml/api/services/all"
        services_response = requests.get(services_url, headers=headers)
        services_data = json.loads(services_response.text)

        for i in range(0, len(services_data)):
            services[i] = services_data[i]['service_name']
        services_sorted = dict(sorted(services.items(), key = lambda kv:kv[1]))

        subscriptions_service_name = {}
        subscriptions_cost = {}
        subscriptions_renewal = {}
        subscriptions_id = {}
        subscriptions_url = "https://api.subtracker.ml/api/customers/getsubscriptions?customer_email=" + request.user.email
        subscriptions_response = requests.get(subscriptions_url, headers=headers)
        if subscriptions_response.text == "No data returned":
            return render(request,"subscriptions.html", {'services': services_sorted})
        else:
            #logger.debug(subscriptions_response.text)
            subscriptions_data = json.loads(subscriptions_response.text)
            return render(request,"subscriptions.html", {'services': services_sorted, 'subscriptions_data':subscriptions_data})

def index(request):
	if request.method == "POST":
		message_name = request.POST['name']
		message_email = request.POST['email']
		message_subject = request.POST['subject']
		message = request.POST['message']
		
		send_mail(
		'Message from' + message_name + ':' + message_subject,
		message,
		message_email,
		['subtrackertest@gmail.com'],
		fail_silently=False)
	else:
		return render(request,"index.html")
		

subtracker_ui/frontend/templates/aboutus.html
<!DOCTYPE html>
<html lang="en">
	
<head>
	<title>SubTracker</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="style.css">
</head>

<body>
	
	<header>
		<div class="container">
		<a href="index.html"><img id="logo" src="images/subtracker.png" alt="SubTracker"></a>
		<nav>
			<ul>
			<li><a href="aboutus.html">About</a></li>
			<li><a href="contact.html">Contact</a></li>
			<li><a href="loginsignup.html">Log In</a></li>
			</ul>
		</nav>
		</div>		
	</header>
	
</body>
</html>

subtracker_ui/frontend/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>SubTracker</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">  
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Subscription management service">
    <meta name="keywords" content="subscription, track subscription, manage subscription, subtracker, track sub, manage subscription">
    <meta name="author" content="SubTracker Team">
    <!--Favicon-->
    <link rel="icon" href='images/subtracker.ico'>
    <!--Bootstrap Default CSS-->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!--Stylesheet CSS-->
    {% load static %}
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!--Material Icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <!--Bootstrap JS-->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
	<style type="text/css">.dropdown-item { padding-left: 0.5rem; padding-right: 0.5rem }</style>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="20">
	<header>
	<nav class="navbar fixed-top navbar-expand-lg navbar-light navbar-custom shadow">
	   <div class="container">
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    	   <span class="navbar-toggler-icon"></span>
		  </button>
		  <a class="navbar-brand" href="{% url 'index' %}">
              
            {% load static %}
              <img src="{% static 'images/SubTracker.svg' %}" height="40" alt="SubTracker logo" id="logo"></a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link active" href="#index">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="#aboutus">About Us</a></li>
	       <li class="nav-item"><a class="nav-link" href="#contactus">Contact Us</a></li>
            {% if request.user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'subscriptions' %}">Subscriptions</a></li>
            {% else %}
            {% endif %}
        </ul>
   {% if request.user.is_authenticated %}
	   <p class="my-auto welcome">Welcome {{ request.user.first_name }}</p>
  <ul class="navbar-nav">

      <div class="dropdown dashboard">
        <a class="nav-link my-auto p-0" role="button" id="Dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="material-icons">account_circle</i>
  </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="Dropdown">
          <a class="dropdown-item" href="{% url 'profile' %}"><i class="material-icons float-left mr-2" height="auto">settings</i>Profile</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'logout' %}"><i class="material-icons float-left mr-2" height="auto">exit_to_app</i>Log Out</a>
        
				</div>
      </div>
  </ul>
{% else %}
			 <a class="btn my-2 signinButton" href="{% url 'social:begin' 'azuread-b2c-oauth2' %}">Sign Up / Login</a>
{% endif %}
	    </div>
	   </div>
    </nav>
<!-- End of nav -->
</header>
<main>
<!-- Home -->
<div id="index" class="jumbotron jumbotron-custom-home">
<div class="container ">
    <div class="row">
        <div class="col-sm-8 col-md-5 mx-auto ctainfo">
        <h1 class="display-4 ">Forgot to cancel a subscription?</h1>
        <p class="lead">No more forgetting. Stop paying for unused subscriptions. SubTracker can help you track and manage your subscriptions.</p>
        {% if request.user.is_authenticated %}
        <a class="btn my-4 my-sm-0 ctaButton" href="{% url 'subscriptions' %}">My Subscriptions</a>
        {% else %}
	    <a class="btn my-4 my-sm-0 ctaButton" href="{% url 'social:begin' 'azuread-b2c-oauth2' %}">Start Saving Now</a>
        {% endif %}
    </div>
    {% load static %}
        <img class="col-md-6 ml-auto p-0 ctaimg" src="{% static 'images/laptop.jpg' %}" alt="pc" width="300" height="300">
    </div>
</div>
</div>
<!-- About Us -->
<div id="aboutus" class="jumbotron jumbotron-custom-about">
    <div class="container">
    <div class="row">
        <div class="col-sm-8 col-md-6 text-center m-auto">
            <h1 class="display-4">Our Story</h1>
            <p class="lead">During a meeting, our team realized the amount of subscriptions people have nowadays. One of the problems that consumers face is the amount of subscriptions they have. From this, we decided to create a platform that would help users manage all of their subscriptions. </p>
        </div>
        <div class="col-sm-8 col-md-6 mx-auto my-auto p-5 aboutimg">
            <img class="aboutimg" src={% static 'images/story.jpg' %} alt="Meeting at table">
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 col-md-6 mx-auto my-auto p-5 aboutimg">
            <img class="aboutimg" src={% static 'images/goal.jpg' %} alt="Person using laptop">
        </div>
        <div class="col-sm-8 col-md-6 text-center mx-auto my-auto">
            <h1 class="display-4">Our Goal</h1>
            <p class="lead">At SubTracker, we want our users to users feel at ease while fully utilizing SubTracker to track and manage their subscriptions. We want to make the experience simple and easy for users to track and manage their subscriptions. </p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 col-md-6 text-center mx-auto my-auto">
            <h1 class="display-4">Our Mission</h1>
            <p class="lead">Our mission is to help users control and manage their evergrowing list of subscriptions. At the end of the day, people shouldn't pay for subscriptions they don't use. Consumers should be able to enjoy all of their subscriptions while saving as much as they can. </p>
        </div>
        <div class="col-sm-8 col-md-6 text-center mx-auto my-auto p-5 ">
            <img class="aboutimg" src={% static 'images/mission.jpg' %} alt="Person on a MacBook">
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-12 text-center mx-auto my-auto">
            <h1 class="display-4 my-5">Our Team</h1>
            <h4>Elsa Cifuentes</h4>
            <p>Project Manager</p>
            <div class="col-sm-6 float-left">
            <h4>Jason Semon</h4>
            <p>DevOps, Architect, Engineer</p>
            <h4>Gibson Sanchez</h4>
            <p>Backend Developer</p>
            </div>
            <div class="col-sm-6 float-right">
            <h4>Desmond Lee</h4>
            <p>Frontend Designer</p>
            <h4>Wynne Kwok</h4>
            <p>Business Analyst</p>
            </div>
        </div>
    </div>
    </div>
</div>
<!-- Contact Us -->
<div id="contactus" class="jumbotron jumbotron-fluid jumbotron-custom-contact">
    <div class="container">
        <h1 class="h1-responsive text-center my-4 display-4">Contact Us</h1>
        <p class="lead text-center w-responsive mx-auto mb-5">Have a question or a suggestion? Our team will gladly assist you with any of your suggestions, questions, or concerns.</p>
        <div class="row">
        <div id="form-field" class="col-md-6 mb-md-0 mb-5">
        <form id="contact-form" name="contact-form" action="#" method="post">
            {% csrf_token %}
        <div class="row">
        <div class="col-md-6">
            <div class="md-form mb-0">
                <input type="text" id="name" name="name" class="form-control" placeholder="" pattern="[a-zA-Z]+" required>
                <label for="name" class="">Name</label>
            </div>
        </div>
        <div class="col-md-6">
            <div class="md-form mb-0">
                <input type="text" id="email" name="email" class="form-control" placeholder="" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" required>
                <label for="email" class="">Email</label>
            </div>
        </div>
        </div>
        <div class="row">
        <div class="col-md-12">
            <div class="md-form mb-0">
                <input type="text" id="subject" name="subject" class="form-control">
                <label for="subject" class="">Subject</label>
            </div>
        </div>
        </div>
        <div class="row">
        <div class="col-md-12">
            <div class="md-form">
                <textarea type="text" id="message" name="message" rows="10" class="form-control  md-textarea" placeholder="" required></textarea>
                <label for="message">Message</label>
            </div>
        </div>
        </div>         
        <div class="text-center">
            <button class="btn my-2 my-sm-0 submitbutton m-auto" type="submit">Submit</button>
        </div>
        </form>
        </div>
        <div id="contact-success" class="m-auto" style="display:none">
            <div class="row text-center m-auto justify-content-center ">
            <div class="col-md-9">
                <h1 class="display-4">Thank you.</h1>
                <p class="lead">Your message has been received. We will get back to you as soon as possible!</p>
            </div>
            </div>
        </div>
        <div class="col-md-4 mx-auto mt-2 text-center justify-content-center">
            <ul class="contact-list">
                <li><i class="material-icons mt-5">place</i>
                    <p>55 Lexington Ave, New York, NY 10010</p>
                </li>

                <li><i class="material-icons mt-5">phone</i>
                    <p><a href="tel:646-312-1000">(646) 312-1000</a></p>
                </li>
                <li><i class="material-icons mt-5">email</i>
                    <p><a href="mailto:contact@subtracker.com">contact@subtracker.com</a><p></p>
                </li>
            </ul>
        </div>
    </div>
    </div>
</div>
</main>
<footer>
    <div class="container">
		  <div class="copyright">
		      &copy; 2020 SubTracker <br>
		      All Rights Reserved
		  </div>
	   <ul class="footernav">
        <div class ="row">
            <div class ="col-md-3 pb-3">
                <h6>Information</h6>
                <li>
                    <a href="#index">Home</a>
                </li>
                <li>
                    <a href="#aboutus">About Us</a>
                </li>
	            <li>
                    <a href="#contactus">Contact Us</a>
                </li>
            </div>
            <div class= "col-md-3">
                <h6>Account</h6>
                {% if request.user.is_authenticated %}
                <li>
                    <a href="{% url 'logout' %}">Log Out</a>
                </li>
                <li>
                    <a href="{% url 'profile' %}">Settings</a>
                </li>
                <li>
                    <a href="{% url 'subscriptions' %}">Subscriptions</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'social:begin' 'azuread-b2c-oauth2' %}">Sign Up / Login</a>
                </li>
                {% endif %}
            </div>
        </div>
       </ul>
    </div>
</footer>
<script>$(document).ready(function() {
    $("#contact-form").submit(function(e) {
        event.preventDefault()
        $("#form-field").hide();
        $("#contact-success").show();
    });
});
</script>
</body>
</html>

subtracker_ui/frontend/templates/logout.html
<!DOCTYPE html>
<html lang="en">
    <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><style id="stndz-style"></style>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="subtracker.ico">

    <title>SubTracker | Sign In</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    {% load static %}
  <link rel="stylesheet" href="{% static 'css/signin.css' %}">
  </head>
<body>
<p> You've successfully logged out</p>
</body>
</html>

subtracker_ui/frontend/templates/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en"><head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Subscription management service">
    <meta name="keywords" content="subscription, track subscription, manage subscription, subtracker, track sub, manage subscription">
    <meta name="author" content="SubTracker Team">
    <title>Profile | SubTracker</title>

    <link rel="shortcut icon" type="image" href="{% static 'subtracker.ico' %}">


    <!-- Bootstrap core CSS -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
    <!--Bootstrap JS-->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    
    <!--Material Icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    
    <!-- Custom styles for this template -->
    <link href="{% static '../css/dashboard.css' %}" rel="stylesheet">
  <style type="text/css">/* Chart.js */
@-webkit-keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}@keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}.chartjs-render-monitor{-webkit-animation:chartjs-render-animation 0.001s;animation:chartjs-render-animation 0.001s;}</style></head>
  <body>
    <nav class="navbar navbar-expand-lg fixed-top navbar-light navbar-custom shadow-sm">
    <div class = "container-fluid">
  <button class="navbar-toggler d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
        <a class="navbar-brand" href="../.."><img src="{% static '../images/SubTracker.svg' %}" height="40" alt="SubTracker logo" id="logo"></a>
	<p class="my-auto pr-2 welcome">Welcome {{ request.user.first_name }}</p>
  <ul class="navbar-nav">

      <div class="dropdown dashboard">
        <a class="nav-link my-auto p-0" role="button" id="Dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="material-icons">account_circle</i>
  </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="Dropdown">
          <a class="dropdown-item" href="{% url 'profile' %}"><i class="material-icons float-left mr-2" height="auto">settings</i>Profile</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'logout' %}"><i class="material-icons float-left mr-2" height="auto">exit_to_app</i>Logout</a>
        </div>
      </div>
  </ul>
        </div>
</nav>

<div class="container-fluid">
  <div class="row">
     <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link row" href="{% url 'subscriptions' %}">
              <i class="material-icons float-left mr-2" height="auto">storage</i>
              Subscriptions
            </a>
          </li>
           <li class="nav-item">
            <a class="nav-link active row" href="{% url 'profile' %}">
            <i class="material-icons float-left mr-2" height="auto">settings</i>
              Profile
            </a>
          </li>
            <li class="nav-item">
            <a class="nav-link row" href="{% url 'index' %}">
            <i class="material-icons float-left mr-2" height="auto">logout</i>
              Log Out
            </a>
          </li>
        </ul>

      </div>
    </nav>

    <main class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <div class="container align-items-center mt-5 mb-5">
          <div class="row">
            <div class ="col-md-4 pt-3 pb-3 border-bottom">
        <h1 class="mb-3">Profile</h1>
        <h4 class="mb-3">Account Information</h4>
        <label for="inputFirstName" class="mb-0">First Name</label>
        <input type="text" id="inputFirstName" class="form-control mb-2" placeholder="" value={{ request.user.first_name }} disabled>
        <label for="inputLastName" class="mb-0">Last Name</label>
        <input type="text" id="inputLastName" class="form-control mb-2" placeholder="" value={{ request.user.last_name }} disabled>
        <label for="inputEmail" class="mb-0" >Email Address</label>
        <input type="email" id="inputEmail" class="form-control mb-2" placeholder="" value={{ request.user }} disabled>
        
              </div>
                  </div>
              <br>
        <div class="row">
            <div class ="col-md-8 pb-3 border-bottom">
        <h1 class="mb-3">Preferences</h1>
        <h4 class="mb-3">Notifications</h4>
        
        <h6>How would you like to be notified?</h6>
        <div class = "mx-auto">
        <form action="/action_page.php">
        <input type="checkbox" id="email" name="email" value="Email" checked>
        <label for="email"> Email</label><br>
        <input title="Feature coming soon!" type="checkbox" id="SMS" name="SMS" value="SMS" disabled>
        <label for="SMS"> SMS/Text Message</label><br>
        <input class="mt-3" type="submit" value="Save">
        </form>
        </div>
              </div>
      </div>
    </div>
    </main>

  </div>
    </div>
	<footer>
		<div class="container-fluid">
		<div class="copyright">
		  &copy; 2020 SubTracker <br>
		  All Rights Reserved
		</div>
	   <ul class="footernav">
           <div class ="row">
        <div class ="col-md-3 pb-3">
            <h6>Information</h6>
           <li>
            <a href="#index">Home</a>
        </li>
        <li>
            <a href="#aboutus">About Us</a>
        </li>
	    <li>
            <a href="#contactus">Contact Us</a>
        </li>
            </div>
           
            <div class= "col-md-3">
                <h6>Account</h6>
           <li>
            <a href="{% url 'logout' %}">Log Out</a>
        </li>
        <li>
            <a href="{% url 'profile' %}">Profile</a>
        </li>
	    <li>
            <a href="{% url 'subscriptions' %}">Subscriptions</a>
        </li>
                </div>
            </div>
       </ul>
		</div>
	</footer>
</body></html>

subtracker_ui/frontend/templates/signin.html
<!DOCTYPE html>
<html lang="en">
    <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><style id="stndz-style"></style>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="subtracker.ico">

    <title>SubTracker | Sign In</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    {% load static %}
	<link rel="stylesheet" href="{% static 'css/signin.css' %}">
  </head>

  <body class="text-center">
    <form class="form-signin">
      {% load static %}
      <a href="index.html"><img class="mb-4" src="{% static 'images/SubTracker.svg' %}" alt="SubTracker logo" height="auto"></a>
      <h1 class="h3 mb-3 font-weight-normal">Sign In</h1>
      <label for="inputEmail" class="sr-only">Email address</label>
      <input type="email" id="inputEmail" class="form-control" placeholder="Email address" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" required autofocus="">
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" required=>
      <div class="checkbox mb-5">
        <label>
            <input type="checkbox" value="remember-me"> Remember Me
        </label>
          <br>
          <a href="#">Forgot password?</a>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <hr class="mb-1">
      <h1 class="h6 mt-0 mb-3 font-weight-normal">New to SubTracker?</h1>
      <a class="btn my-3 my-sm-0 btn-lg btn-primary btn-block" href="signup.html">Create an account</a>
      <p class="mt-3 mb-2 text-muted">© 2020</p>
        
    </form>  
  </body>
</html>

subtracker_ui/frontend/templates/user.html
{% if request.user.is_authenticated %}
    <p>Welcome, {{ request.user.username }}. Thanks for logging in.</p>
{% else %}
    <p>Welcome, new user. Please <a href="/accounts/login">log in.</a></p>
{% endif %}